#!/bin/bash

## Initializing
if [ ! -f ./.htaccess ]; then
	echo "First using.. Initializing script.."
	echo "AddDefaultCharset UTF-8" > .htaccess
	echo "RewriteEngine On" >> .htaccess
	echo "RewriteCond %{REQUEST_URI}  !^/$" >> .htaccess
fi

## functions
if [ "$1" = "add" ]; then
	if [ ! "$3" ]; then
		echo 'Usage for 'add':'
		echo './gaia add <project_name> <url_name>'
	else
		git clone https://github.com/flrngel/FHC-Framework $2/www
		cd $2/www
		./install.sh
		cd ../../
		echo -e "RewriteRule\t^$3(.*)\$\t$2/www/\$1\t[L]" >> .htaccess
	fi
else
	echo "no such command '$1'."
fi
